[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Remappings
remappings = [
	    "forge-std=lib/forge-std/src",
			"@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts",
			"@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts",
			'@openzeppelin/foundry-upgrades=lib/openzeppelin-foundry-upgrades/src',
			"@chainlink/contracts/=lib/chainlink-evm/contracts"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
