// SPDX-License-Identifier: MIT
pragma solidity ^0.8.30;

interface IStakingRouter {
    error StakingRouter_InvalidAmount();
    error StakingRouter_InvalidReceiver();
    error StakingRouter_FailedToTransfer();
    error StakingRouter_InvalidUnderlyingToken();
    error StakingRouter_InvalidStakedToken();

    /// @notice Stakes a specified amount of the underlying token
    /// @param amount The amount to stake
    /// @param receiver The address to receive the staked tokens
    function stake(uint256 amount, address receiver) external;

    /// @notice Unstakes a specified amount of the staked token
    /// @param amount The amount to unstake
    /// @param receiver The address to receive the tokens
    function unstake(uint256 amount, address receiver) external;

    /// @notice Claims any rewards generated by the staking strategy
    function claimRewards() external;

    /// @notice Returns the underlying token accepted by the strategy (e.g., ETH, LINK)
    function getUnderlyingToken() external view returns (address);

    /// @notice Returns the token received after staking (e.g., stETH, rETH)
    function getStakedToken() external view returns (address);

    /// @notice Returns the total amount of underlying tokens managed by the strategy
    function getTotalUnderlying() external view returns (uint256);

    /// @notice Returns the total amount of staked tokens managed by the strategy
    function getTotalStaked() external view returns (uint256);

    /// @notice Returns the current yield of the staking strategy (10000 = 100%)
    function getYieldCurrent() external view returns (uint256);

    /// @notice Returns the estimated yield for a given amount of underlying tokens
    /// @param amount The amount of underlying tokens
    /// @return The estimated yield
    function getYieldPreview(uint256 amount) external view returns (uint256);
}
